### ISSUE TITLE
Generating Maven reports

### ISSUE THREAD

**Issue by mstanleyjones** [ingenieux/jbake-maven-plugin#14]
Can JBake be integrated into Maven in the same way as the Maven site plugin, to generate the Maven reports such as the dependency management, mailing lists, team page, etc?

**Comment by jonbullock** [comment]
Not at present but this would be a great use case for the plugin/extension system that's being explored here: https://github.com/jbake-org/jbake/wiki/Plugin-System

**Comment by aldrinleal** [comment]
@mstanleyjones we do have integration as a lifecycle only. Do you have any project in mind?
